#服务器相关配置
server:
  port: 8089
  servlet:
    context-path: /demo
    session:
      timeout: 30m

#系统自定义参数
system:
  swagger-open: false              #是否开启swagger (true/false)
  kaptcha-open: false              #是否开启登录时验证码 (true/false)
  session-invalidate-time: 1800    #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 600 #多久检测一次失效的session 单位：秒

#spring相关配置
spring:
  profiles:
    active: @spring.active@
  mvc:
    view:
      prefix: /views
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
      exclude: static/**,views/**
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  session:
    store-type: redis

#mybatis-plus相关配置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  typeAliasesPackage: com.example.demo.common.model
  global-config:
    db-config:
      logic-not-delete-value: N
      logic-delete-value: Y
    refresh: true

#静态资源版本号
customize:
  resources:
    version: 1.1

#日志
log.path: D:\\logs
